import { Footer } from "@/components/footer";
import { HeaderNoScroll } from "@/components/headerNoScroll";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen flex flex-col", inter.className)}>
        <HeaderNoScroll />
        <div className="flex flex-col items-start justify-start flex-1">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
